enableGlobalCache: true

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.1.0.cjs

defaultSemverRangePrefix: ''

packageExtensions:
  eslint-config-airbnb-typescript@18:
    peerDependencies:
      typescript-eslint: ^7.0.0
    peerDependenciesMeta:
      '@typescript-eslint/eslint-plugin':
        optional: true
      '@typescript-eslint/parser':
        optional: true
