apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleman
  labels:
    app: middleman
spec:
  selector:
    matchLabels:
      app: middleman
  template:
    metadata:
      labels:
        app: middleman
    spec:
      containers:
        - name: middleman
          image: middleman
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: middleman
            - secretRef:
                name: middleman
