db:
  uri: "mongodb://localhost/enmon-adapter"

thermometers:
  - model: ""
    dataSourceUrl: ""
    enmon:
      env: "app"
      customerId: ""
      devEUI: ""
      token: ""

wattrouters:
  - model: "Mx"
    baseURL: ""
    targets:
      - env: "app"
        customerId: ""
        devEUI: ""
        token: ""
