name: CI

on:
  push:
    branches:
      - master
      - deploy
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
  install:
    runs-on: ubuntu-24.04
    outputs:
      pkgman: "pnpm"
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.x
          cache: "pnpm"

      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: pnpm-v1-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

      - run: pnpm install --frozen-lockfile

  lint:
    needs: [install]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.x
          cache: ${{ needs.install.outputs.pkgman }}

      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ needs.install.outputs.pkgman }}-v1-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

      - run: ${{ needs.install.outputs.pkgman }} run lint

  build:
    needs: [install]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.x
          cache: ${{ needs.install.outputs.pkgman }}

      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ needs.install.outputs.pkgman }}-v1-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

      - run: ${{ needs.install.outputs.pkgman }} build

      - run: tar -cv dist/ package.json pnpm-lock.yaml | gzip -v -9 > dist-${{ github.sha }}.tar.gz

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ github.sha }}
          path: dist-${{ github.sha }}.tar.gz

  docker_image:
    needs: [install]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: pnpm-v1-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: false
          load: true
          tags: ghcr.io/${{ github.repository }}:${{github.sha}}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  test:
    needs: [install]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.x
          cache: ${{ needs.install.outputs.pkgman }}

      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ needs.install.outputs.pkgman }}-v1-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

      - run: ${{ needs.install.outputs.pkgman }} run test
